# k8s-metrics-api-chart/templates/clusterrolebinding.yaml
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-metrics-api.fullname" . }}-reader-binding
  labels:
    {{- include "k8s-metrics-api.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-metrics-api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "k8s-metrics-api.fullname" . }}-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}