{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "k8s-metrics-api.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "k8s-metrics-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "k8s-metrics-api.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    {{- with .Values.networkPolicy.ingress.from }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.application.containerPort }}
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow Kubernetes API access
  - to: []
    ports:
    - protocol: TCP
      port: 443
  {{- with .Values.networkPolicy.egress.additional }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}