# k8s-metrics-api-chart/templates/secret.yaml
{{- if .Values.application.createAuthSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-metrics-api.authTokenSecretName" . }}
  labels:
    {{- include "k8s-metrics-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.application.authSecretKey }}: {{ .Values.application.authToken | b64enc | quote }}
{{- end }}