// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	prometheus "github.com/prometheus/client_golang/prometheus"
	mock "github.com/stretchr/testify/mock"
)

// Collector is an autogenerated mock type for the Collector type
type Collector struct {
	mock.Mock
}

type Collector_Expecter struct {
	mock *mock.Mock
}

func (_m *Collector) EXPECT() *Collector_Expecter {
	return &Collector_Expecter{mock: &_m.Mock}
}

// Collect provides a mock function with given fields: _a0
func (_m *Collector) Collect(_a0 chan<- prometheus.Metric) {
	_m.Called(_a0)
}

// Collector_Collect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collect'
type Collector_Collect_Call struct {
	*mock.Call
}

// Collect is a helper method to define mock.On call
//   - _a0 chan<- prometheus.Metric
func (_e *Collector_Expecter) Collect(_a0 interface{}) *Collector_Collect_Call {
	return &Collector_Collect_Call{Call: _e.mock.On("Collect", _a0)}
}

func (_c *Collector_Collect_Call) Run(run func(_a0 chan<- prometheus.Metric)) *Collector_Collect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(chan<- prometheus.Metric))
	})
	return _c
}

func (_c *Collector_Collect_Call) Return() *Collector_Collect_Call {
	_c.Call.Return()
	return _c
}

func (_c *Collector_Collect_Call) RunAndReturn(run func(chan<- prometheus.Metric)) *Collector_Collect_Call {
	_c.Run(run)
	return _c
}

// Describe provides a mock function with given fields: _a0
func (_m *Collector) Describe(_a0 chan<- *prometheus.Desc) {
	_m.Called(_a0)
}

// Collector_Describe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Describe'
type Collector_Describe_Call struct {
	*mock.Call
}

// Describe is a helper method to define mock.On call
//   - _a0 chan<- *prometheus.Desc
func (_e *Collector_Expecter) Describe(_a0 interface{}) *Collector_Describe_Call {
	return &Collector_Describe_Call{Call: _e.mock.On("Describe", _a0)}
}

func (_c *Collector_Describe_Call) Run(run func(_a0 chan<- *prometheus.Desc)) *Collector_Describe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(chan<- *prometheus.Desc))
	})
	return _c
}

func (_c *Collector_Describe_Call) Return() *Collector_Describe_Call {
	_c.Call.Return()
	return _c
}

func (_c *Collector_Describe_Call) RunAndReturn(run func(chan<- *prometheus.Desc)) *Collector_Describe_Call {
	_c.Run(run)
	return _c
}

// UpdateMetrics provides a mock function with no fields
func (_m *Collector) UpdateMetrics() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetrics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Collector_UpdateMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetrics'
type Collector_UpdateMetrics_Call struct {
	*mock.Call
}

// UpdateMetrics is a helper method to define mock.On call
func (_e *Collector_Expecter) UpdateMetrics() *Collector_UpdateMetrics_Call {
	return &Collector_UpdateMetrics_Call{Call: _e.mock.On("UpdateMetrics")}
}

func (_c *Collector_UpdateMetrics_Call) Run(run func()) *Collector_UpdateMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Collector_UpdateMetrics_Call) Return(_a0 error) *Collector_UpdateMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Collector_UpdateMetrics_Call) RunAndReturn(run func() error) *Collector_UpdateMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewCollector creates a new instance of Collector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Collector {
	mock := &Collector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
